#!/usr/bin/env python
# Copyright (C) 2012 Nathan Charles
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

def usage():
    """Prints usage options when called with no arguments or with invalid arguments
    """
    print """usage: [options]
   -a    current
   -l    length
   -p    phase [default 1]
   -v    voltage [default 240]
   -s    size
   -h    help
    """

import ee

#def solve()
def solve(args, **kwargs):
    a =  eval(args['current'])
    oc = a * 1.25
    print "Continous Current: %s" % a
    ocp =ee.findOCP(oc)
    print "OCP Size: %s" % ocp
    l = eval(args['length'])
    v = args['voltage']
    pf = args['powerfactor']
    t = args['temp']
    percent = args['drop']
    material = 'CU'
    if args['aluminum']:
        material = 'AL'
    c = args['conduit']
    vd = args['voltage'] * percent/100.0
    size = args['size']
    r = 0
    if size:
        tconductor = ee.conductor(size, material)
        r = ee.resistance( tconductor,c,pf, t)
        vd = 2.0* a * r * l/1000.0
        print "Voltage drop: %sV" % vd
        print "Percent drop: %s%%" % (vd * 100/v)
        ee.checkAmpacity(tconductor, ocp)

    else:
        print "Allowed Voltage drop: %sV" % vd
        #vd = 2*a*l*r/1000
        r = (vd*1000)/(2.0 * a*l)
        print "Resistance: %s" % r
        sets = 1
        while 1:
            conductor = ee.findConductor((r*sets),material,c,pf,t)
            if conductor:
                break
            sets +=1

        if sets > 1:
            print "WARNING: %s sets of conductors" % sets
        print "Conductor %s" % conductor
        ee.checkAmpacity(conductor, ocp/sets)

if __name__ == "__main__":
    import argparse
    import sys
    parser = argparse.ArgumentParser(description='Voltage Drop/Rise Calculator')
    parser.add_argument('-a', '--aluminum',action='store_true')
    parser.add_argument('-c', '--current',required=True,help="accepts basic math") #evaluated to allow command line math
    parser.add_argument('-d', '--drop',type=float,default=1,help="Voltage Drop/Rise in percent")
    parser.add_argument('-v', '--voltage',type=float,default=240)
    parser.add_argument('-f', '--powerfactor',type=float,default=-1)
    parser.add_argument('-l', '--length',required=True,help="accepts basic math")#evaluated to allow command line math
    parser.add_argument('-p', '--conduit',type=str,default='PVC')
    parser.add_argument('-s', '--size',type=str,help="wire size")
    parser.add_argument('-t', '--temp',type=float,help="actual conductor temp",default=75)
    #parser.print_help()
    args = vars(parser.parse_args())
    #solve(args['current'],args['length'],args['voltage'],args['drop'])
    #print args

    try:
        #start program
        solve(args)

    except (KeyboardInterrupt, SystemExit):
        sys.exit(1)
    except:
        raise
